### ISSUE TITLE
在example目录下，flutter项目打开正常，但是是native工程打开后点击press出来是白屏怎么破呀

### ISSUE THREAD

**Issue by sevenOnClass** [CaffreySun/iOS_Flutter_Hybrid_Project#1]

**Comment by sevenOnClass** [comment]
debug环境下

**Comment by CaffreySun** [comment]
@sevenOnClass 使用脚本打包处产物后，然后在native工程运行白屏？

**Comment by sevenOnClass** [comment]
对的，
1)my_flutter，build_ios.sh debug，和build_ios.sh debug都尝试过，目前.build_ios文件中有个debug目录，里面是有product的；
2)my_native中prodfile: 中**我修改了FLUTTER_APP_VERSION='1.1.1'(这个应该没有影响吧)**；FLUTTER_DEBUG_APP是true，表示调试；FLUTTER_APP_PATH也是默认的路径（就不走git配置了）；3）执行pod install，debug环境下表现正常命令行正常，但是在native工程运行时，点击press运行就是白屏
4）你那边能复现嘛，我需要提供什么资源？

**Comment by sevenOnClass** [comment]
第二个问题，我在my_flutter中，使用build_ios.sh release, 怎么没有release的产物呢；FLUTTER_APP_VERSION这个版本号，和flutter项目中哪个参数是关联的呢

**Comment by CaffreySun** [comment]
@sevenOnClass 我先试试能不能复现。

**Comment by CaffreySun** [comment]
@sevenOnClass 问题已经修复
