### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by OHeroJ** [CaffreySun/iOS_Flutter_Hybrid_Project#13]
项目中我们是引入了 flutter_wrapper, 那么对于 flutter 相关的命令，个人觉得像

```sh
 ${FLUTTER_ROOT}/bin/flutter clean

 ${FLUTTER_ROOT}/bin/flutter build ios --${BUILD_MODE}
```

可以替换为 

```sh
./flutterw  clean
./flutterw build ios  --${BUILD_MODE}
```

`${FLUTTER_ROOT}/bin/flutter` 替换为 `./flutterw`

**Comment by CaffreySun** [comment]
收到

**Comment by CaffreySun** [comment]
[${FLUTTER_ROOT}/bin/flutter —> ${FLUTTER_WRAPPER}](https://github.com/CaffreySun/iOS_Flutter_Hybrid_Project/commit/5c57179c3b82b49447c1a9cb37a94b973b8b8137)
