### ISSUE TITLE
flutter 1.5+ 做适配了么?

### ISSUE THREAD

**Issue by OHeroJ** [CaffreySun/iOS_Flutter_Hybrid_Project#16]
flutter 1.5+ 做适配了么? 刚试了下，debug ， attatch 不成功

**Comment by CaffreySun** [comment]
还没有，这两天我适配一下

**Comment by CaffreySun** [comment]
我这边可以正常使用，你报了什么错

**Comment by OHeroJ** [comment]
debug 模拟器, 用 flutter attatch --debug-port=xxx, 连接不上

**Comment by CaffreySun** [comment]
使用./flutterw attatch 呢？
我使用./flutterw attach也链接不上，flutter 的这个issuse[#31854](https://github.com/flutter/flutter/issues/31854)说在master分支修复了

**Comment by OHeroJ** [comment]
应该是 attach 姿势不对
