### ISSUE TITLE
flutterhelper.rb 脚本中  查找 podspec 问题

### ISSUE THREAD

**Issue by manajay** [CaffreySun/iOS_Flutter_Hybrid_Project#18]
![image](https://user-images.githubusercontent.com/13750333/59996629-6c1e7000-968d-11e9-9998-1a31cdebfa77.png)
![image](https://user-images.githubusercontent.com/13750333/59996751-cddeda00-968d-11e9-8ab9-bd8c609f3911.png)

**Comment by manajay** [comment]
产物的 pod 路径  .flutter_release拼接上 product

**Comment by hllGitHub** [comment]
请问`.flutter_release`中怎么保证只有`product`部分呢？

```
def update_flutter_app(path, url, branche)
    # 如果flutter项目不存在，则clone
    if !File.exist?(path)
        `git clone #{url} #{path}`
    end
    `cd #{path} && git fetch --all -v && \
    git reset --hard origin/master && \
    git pull && \
    git checkout -B #{branche} origin/#{branche}`
end
```

这段代码并不能实现这种效果

**Comment by zhubinsheng** [comment]
这个问题怎么解决的啊
