### ISSUE TITLE
编译产物在链接时报错

### ISSUE THREAD

**Issue by xiubojin** [CaffreySun/iOS_Flutter_Hybrid_Project#19]
我集成了flutter_boost，运行shell脚本，编译产物有：
App.framework
Flutter.framework
flutter_boost
xservice_kit
GeneratedPluginRegistrant
后面3个是插件，这几个产物都做使用pod管理，做成了私有repo。
xservice_kit依赖Flutter.framework，编译时报错：

ld: warning: Could not find auto-linked framework 'Flutter'
Undefined symbols for architecture arm64:
  "_FlutterMethodNotImplemented", referenced from:
      -[XserviceKitPlugin handleMethodCall:result:] in XserviceKitPlugin.o
  "_OBJC_CLASS_$_FlutterEventChannel", referenced from:
      objc-class-ref in FlutterChannelManager.o
     (maybe you meant: _OBJC_CLASS_$_FlutterEventChannelHandler)
  "_OBJC_CLASS_$_FlutterMethodChannel", referenced from:
      objc-class-ref in FlutterChannelManager.o
      objc-class-ref in XserviceKitPlugin.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

xcode的build_settings配置检查了N遍感觉没什么问题。

模拟器编译没问题，真机就会报这个错误。

**Comment by serge66** [comment]
@xiubojin  哈喽,遇见了同样的问题,请问你解决了吗
