### ISSUE TITLE
iOS 集成 flutter(module)

### ISSUE THREAD

**Issue by geogie** [CaffreySun/iOS_Flutter_Hybrid_Project#6]
大佬，ios中集成flutter(module)。怎么处理从flutter界面退回到ios项目？我目前遇到从flutter退回ios项目的时候flutter的所有生命周期没有回调，导致再次进入flutter的时候没有重新绘制界面。不知道你遇到过没

**Comment by CaffreySun** [comment]
flutter页面消失后没有释放吗？

**Comment by xubillde** [comment]
最后解决了吗？我这边暂时销毁引擎了

**Comment by geogie** [comment]
就是flutter官方提供的那种plugin方式依赖，会出现在加载plugin的时候页面就开始加载了，退出界面后就是不走flutter的生命周期。
目前采用了另外一种方案(非plugin)方式依赖。

**Comment by geogie** [comment]
@CaffreySun 没有走释放的回调。

**Comment by geogie** [comment]
@LDXu 销毁引擎？你不是plugin方式依赖的吗？那个引擎是在AppDelegate中初始化的。那你再次进入怎么处理的？

**Comment by geogie** [comment]
大佬们可以加下好友讨论下我的qq:1063658094

**Comment by geogie** [comment]
@LDXu @CaffreySun 大佬们,我可以加下你们好友讨论下。我的qq:1063658094

**Comment by xubillde** [comment]
引擎是AppDelegate懒加载方式的。退出的时候，先把引擎给一个变量，然后把AppDelegate暴露的引擎赋成nil，最后这个变量引擎调用销毁方法。不知道有没有问题，来回切了几下，内存好像还行

**Comment by CaffreySun** [comment]
我忘记了1.2.1引擎变成了AppDelegate时初始化。我还在用1.0.0；

**Comment by CaffreySun** [comment]
@geogie 可以来gitter聊 https://gitter.im/iOS_Flutter_Hybrid_Project/community?utm_source=share-link&utm_medium=link&utm_campaign=share-link
